services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: slash-nginx-rtmp
    ports:
      - "1935:1935"  # RTMP input for OBS
      - "80:80"      # HLS output over HTTP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/tmp/hls